default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  pool: 5

development:
  <<: *default
  database: members_only_development
  host: db
  password: password

test:
  <<: *default
  database: members_only_myapp_test

production:
  <<: *default
  database: members_only_production
  host: <%= ENV['DATABASE_URL'] %>